import type { IconType } from "react-icons";
import {
    FaArrowUpRightFromSquare,
    FaBookOpen,
    FaCalendarDays,
    FaChartLine,
    FaEnvelope,
    FaGlobe,
    FaHeadphones,
    FaLink,
    FaMapLocationDot,
    FaPhone,
    FaPodcast,
    FaStore,
} from "react-icons/fa6";
import {
    SiAmazon,
    SiAmazons3,
    SiAmazonsqs,
    SiAndroid,
    SiAngular,
    SiApollographql,
    SiApple,
    SiAppstore,
    SiAsana,
    SiAtlassian,
    SiAwsamplify,
    SiBehance,
    SiBinance,
    SiBitcoin,
    SiBitbucket,
    SiBitly,
    SiBlogger,
    SiCanva,
    SiCodepen,
    SiCodesandbox,
    SiDailymotion,
    SiDeviantart,
    SiDiscord,
    SiDribbble,
    SiDropbox,
    SiDuckduckgo,
    SiEtsy,
    SiEventbrite,
    SiEvernote,
    SiFacebook,
    SiFigma,
    SiFirefox,
    SiGithub,
    SiGitlab,
    SiGmail,
    SiGoogle,
    SiGoogledrive,
    SiGooglemaps,
    SiHackerone,
    SiHeroku,
    SiInstagram,
    SiIntel,
    SiKickstarter,
    SiKotlin,
    SiLinkedin,
    SiLinux,
    SiMaildotru,
    SiMedium,
    SiMongodb,
    SiNotepadplusplus,
    SiNotion,
    SiNpm,
    SiOpenai,
    SiPatreon,
    SiPaypal,
    SiPinterest,
    SiReddit,
    SiRedhat,
    SiSalesforce,
    SiSamsung,
    SiShopify,
    SiSlack,
    SiSnapchat,
    SiSoundcloud,
    SiSpotify,
    SiStackoverflow,
    SiSteam,
    SiStripe,
    SiTelegram,
    SiTiktok,
    SiTrello,
    SiTumblr,
    SiTwitch,
    SiUber,
    SiUnity,
    SiUnsplash,
    SiVimeo,
    SiWechat,
    SiWhatsapp,
    SiWikipedia,
    SiWordpress,
    SiX,
    SiYoutube,
    SiZoom,
} from "react-icons/si";

export type IconOption = {
    id: string;
    label: string;
    icon: IconType;
};

export const iconOptions: IconOption[] = [
    { id: "si:instagram", label: "Instagram", icon: SiInstagram },
    { id: "si:youtube", label: "YouTube", icon: SiYoutube },
    { id: "si:tiktok", label: "TikTok", icon: SiTiktok },
    { id: "si:twitter", label: "X (Twitter)", icon: SiX },
    { id: "si:facebook", label: "Facebook", icon: SiFacebook },
    { id: "si:linkedin", label: "LinkedIn", icon: SiLinkedin },
    { id: "si:github", label: "GitHub", icon: SiGithub },
    { id: "si:dribbble", label: "Dribbble", icon: SiDribbble },
    { id: "si:behance", label: "Behance", icon: SiBehance },
    { id: "si:pinterest", label: "Pinterest", icon: SiPinterest },
    { id: "si:spotify", label: "Spotify", icon: SiSpotify },
    { id: "si:twitch", label: "Twitch", icon: SiTwitch },
    { id: "si:discord", label: "Discord", icon: SiDiscord },
    { id: "si:reddit", label: "Reddit", icon: SiReddit },
    { id: "si:medium", label: "Medium", icon: SiMedium },
    { id: "si:notion", label: "Notion", icon: SiNotion },
    { id: "si:slack", label: "Slack", icon: SiSlack },
    { id: "si:shopify", label: "Shopify", icon: SiShopify },
    { id: "si:etsy", label: "Etsy", icon: SiEtsy },
    { id: "si:patreon", label: "Patreon", icon: SiPatreon },
    { id: "si:soundcloud", label: "SoundCloud", icon: SiSoundcloud },
    { id: "si:telegram", label: "Telegram", icon: SiTelegram },
    { id: "si:whatsapp", label: "WhatsApp", icon: SiWhatsapp },
    { id: "si:snapchat", label: "Snapchat", icon: SiSnapchat },
    { id: "si:vimeo", label: "Vimeo", icon: SiVimeo },
    { id: "si:figma", label: "Figma", icon: SiFigma },
    { id: "si:kickstarter", label: "Kickstarter", icon: SiKickstarter },
    { id: "si:amazon", label: "Amazon", icon: SiAmazon },
    { id: "si:google", label: "Google", icon: SiGoogle },
    { id: "si:apple", label: "Apple", icon: SiApple },
    { id: "si:android", label: "Android", icon: SiAndroid },
    { id: "si:appstore", label: "App Store", icon: SiAppstore },
    { id: "si:asana", label: "Asana", icon: SiAsana },
    { id: "si:atlassian", label: "Atlassian", icon: SiAtlassian },
    { id: "si:awsamplify", label: "AWS Amplify", icon: SiAwsamplify },
    { id: "si:amazons3", label: "Amazon S3", icon: SiAmazons3 },
    { id: "si:amazonsqs", label: "Amazon SQS", icon: SiAmazonsqs },
    { id: "si:angular", label: "Angular", icon: SiAngular },
    { id: "si:apollographql", label: "Apollo GraphQL", icon: SiApollographql },
    { id: "si:bitcoin", label: "Bitcoin", icon: SiBitcoin },
    { id: "si:binance", label: "Binance", icon: SiBinance },
    { id: "si:bitbucket", label: "Bitbucket", icon: SiBitbucket },
    { id: "si:bitly", label: "Bitly", icon: SiBitly },
    { id: "si:blogger", label: "Blogger", icon: SiBlogger },
    { id: "si:canva", label: "Canva", icon: SiCanva },
    { id: "si:codepen", label: "CodePen", icon: SiCodepen },
    { id: "si:codesandbox", label: "CodeSandbox", icon: SiCodesandbox },
    { id: "si:dailymotion", label: "Dailymotion", icon: SiDailymotion },
    { id: "si:deviantart", label: "DeviantArt", icon: SiDeviantart },
    { id: "si:dropbox", label: "Dropbox", icon: SiDropbox },
    { id: "si:duckduckgo", label: "DuckDuckGo", icon: SiDuckduckgo },
    { id: "si:eventbrite", label: "Eventbrite", icon: SiEventbrite },
    { id: "si:evernote", label: "Evernote", icon: SiEvernote },
    { id: "si:firefox", label: "Firefox", icon: SiFirefox },
    { id: "si:gitlab", label: "GitLab", icon: SiGitlab },
    { id: "si:gmail", label: "Gmail", icon: SiGmail },
    { id: "si:googledrive", label: "Google Drive", icon: SiGoogledrive },
    { id: "si:googlemaps", label: "Google Maps", icon: SiGooglemaps },
    { id: "si:hackerone", label: "HackerOne", icon: SiHackerone },
    { id: "si:heroku", label: "Heroku", icon: SiHeroku },
    { id: "si:intel", label: "Intel", icon: SiIntel },
    { id: "si:kotlin", label: "Kotlin", icon: SiKotlin },
    { id: "si:linux", label: "Linux", icon: SiLinux },
    { id: "si:maildotru", label: "Mail.ru", icon: SiMaildotru },
    { id: "si:mongodb", label: "MongoDB", icon: SiMongodb },
    { id: "si:npm", label: "npm", icon: SiNpm },
    { id: "si:notepadplusplus", label: "Notepad++", icon: SiNotepadplusplus },
    { id: "si:openai", label: "OpenAI", icon: SiOpenai },
    { id: "si:paypal", label: "PayPal", icon: SiPaypal },
    { id: "si:redhat", label: "Red Hat", icon: SiRedhat },
    { id: "si:salesforce", label: "Salesforce", icon: SiSalesforce },
    { id: "si:samsung", label: "Samsung", icon: SiSamsung },
    { id: "si:stackoverflow", label: "Stack Overflow", icon: SiStackoverflow },
    { id: "si:steam", label: "Steam", icon: SiSteam },
    { id: "si:stripe", label: "Stripe", icon: SiStripe },
    { id: "si:trello", label: "Trello", icon: SiTrello },
    { id: "si:tumblr", label: "Tumblr", icon: SiTumblr },
    { id: "si:uber", label: "Uber", icon: SiUber },
    { id: "si:unity", label: "Unity", icon: SiUnity },
    { id: "si:unsplash", label: "Unsplash", icon: SiUnsplash },
    { id: "si:wechat", label: "WeChat", icon: SiWechat },
    { id: "si:wikipedia", label: "Wikipedia", icon: SiWikipedia },
    { id: "si:wordpress", label: "WordPress", icon: SiWordpress },
    { id: "si:zoom", label: "Zoom", icon: SiZoom },
    { id: "fa:link", label: "Link", icon: FaLink },
    { id: "fa:globe", label: "Website", icon: FaGlobe },
    { id: "fa:email", label: "Email", icon: FaEnvelope },
    { id: "fa:phone", label: "Phone", icon: FaPhone },
    { id: "fa:store", label: "Store", icon: FaStore },
    {
        id: "fa:external",
        label: "External Link",
        icon: FaArrowUpRightFromSquare,
    },
    { id: "fa:book", label: "Read", icon: FaBookOpen },
    { id: "fa:map", label: "Location", icon: FaMapLocationDot },
    { id: "fa:podcast", label: "Podcast", icon: FaPodcast },
    { id: "fa:calendar", label: "Calendar", icon: FaCalendarDays },
    { id: "fa:chart", label: "Analytics", icon: FaChartLine },
    { id: "fa:audio", label: "Audio", icon: FaHeadphones },
];

const iconMap = new Map(iconOptions.map((option) => [option.id, option.icon]));
iconMap.set("si:x", SiX);

export function getIconById(iconId?: string): IconType {
    if (!iconId) {
        return FaLink;
    }

    return iconMap.get(iconId) ?? FaLink;
}
