import type {
    BackgroundConfig,
    CoverConfig,
    StyleConfig,
    ThemeConfig,
} from "@/lib/app-config";

type NonImageBackground = Extract<BackgroundConfig, { type: "solid" | "gradient" }>;
type NonImageCover = Exclude<CoverConfig, { type: "image" }>;

export type ThemeTemplate = {
    id: string;
    name: string;
    description: string;
    tone: "light" | "dark";
    background: NonImageBackground;
    cover: NonImageCover;
    theme: Omit<ThemeConfig, "background">;
    customButtonStyle: Partial<StyleConfig>;
};

const baseTemplates: ThemeTemplate[] = [
    {
        id: "default-light",
        name: "Default Light",
        description: "Matches the seeded default look.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#f8fafc", "#dbeafe", "#e0f2fe"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#dbeafe", "#e0f2fe"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#e2e8f0",
                textColor: "#0f172a",
                bgColor: "#ffffff",
                hoverBorderColor: "#6366f1",
                hoverTextColor: "#4338ca",
                hoverBgColor: "#eef2ff",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#e2e8f0",
                textColor: "#0f172a",
                bgColor: "#ffffff",
                hoverBorderColor: "#6366f1",
                hoverTextColor: "#4338ca",
                hoverBgColor: "#eef2ff",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 80,
                blur: 28,
                radius: 28,

            },
            textColor: "#0f172a",
            hoverAnimation: "lift",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#bae6fd",
            textColor: "#0f172a",
            bgColor: "#f0f9ff",
            hoverBorderColor: "#38bdf8",
            hoverTextColor: "#075985",
            hoverBgColor: "#e0f2fe",
            textAlign: "center",
        },
    },
    {
        id: "aurora-glass",
        name: "Aurora Glass",
        description: "Soft sky gradients with crisp indigo accents.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#f8fafc", "#e0e7ff", "#dbeafe"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#e0e7ff", "#fde68a"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#e2e8f0",
                textColor: "#0f172a",
                bgColor: "#ffffff",
                hoverBorderColor: "#6366f1",
                hoverTextColor: "#312e81",
                hoverBgColor: "#eef2ff",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#e2e8f0",
                textColor: "#0f172a",
                bgColor: "#ffffff",
                hoverBorderColor: "#0ea5e9",
                hoverTextColor: "#075985",
                hoverBgColor: "#e0f2fe",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 78,
                blur: 28,
                radius: 28,

            },
            textColor: "#0f172a",
            hoverAnimation: "float",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#bae6fd",
            textColor: "#0f172a",
            bgColor: "#f0f9ff",
            hoverBorderColor: "#38bdf8",
            hoverTextColor: "#075985",
            hoverBgColor: "#e0f2fe",
            textAlign: "center",
        },
    },
    {
        id: "peach-studio",
        name: "Peach Studio",
        description: "Warm sunrise tones with modern coral highlights.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#fff7ed", "#fde68a", "#fecdd3"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#fde68a", "#fecdd3"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#fed7aa",
                textColor: "#7c2d12",
                bgColor: "#fff7ed",
                hoverBorderColor: "#fb7185",
                hoverTextColor: "#9f1239",
                hoverBgColor: "#ffe4e6",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#fed7aa",
                textColor: "#7c2d12",
                bgColor: "#fff7ed",
                hoverBorderColor: "#f97316",
                hoverTextColor: "#9a3412",
                hoverBgColor: "#ffedd5",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 82,
                blur: 26,
                radius: 28,

            },
            textColor: "#7c2d12",
            hoverAnimation: "lift",
            hoverTransitionMs: 230,
        },
        customButtonStyle: {
            borderColor: "#fdba74",
            textColor: "#7c2d12",
            bgColor: "#ffedd5",
            hoverBorderColor: "#fb7185",
            hoverTextColor: "#9f1239",
            hoverBgColor: "#ffe4e6",
            textAlign: "center",
        },
    },
    {
        id: "mint-cloud",
        name: "Mint Cloud",
        description: "Airy mint glass with teal and jade accents.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#ecfeff", "#d1fae5", "#f0fdfa"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#d1fae5", "#99f6e4"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#d1fae5",
                textColor: "#0f766e",
                bgColor: "#ecfdf5",
                hoverBorderColor: "#14b8a6",
                hoverTextColor: "#115e59",
                hoverBgColor: "#ccfbf1",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#d1fae5",
                textColor: "#0f766e",
                bgColor: "#ecfdf5",
                hoverBorderColor: "#22c55e",
                hoverTextColor: "#166534",
                hoverBgColor: "#dcfce7",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 80,
                blur: 28,
                radius: 28,

            },
            textColor: "#0f766e",
            hoverAnimation: "pop",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#5eead4",
            textColor: "#0f766e",
            bgColor: "#ccfbf1",
            hoverBorderColor: "#2dd4bf",
            hoverTextColor: "#115e59",
            hoverBgColor: "#99f6e4",
            textAlign: "center",
        },
    },
    {
        id: "lilac-bloom",
        name: "Lilac Bloom",
        description: "Lavender hues with a soft rose glow.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#faf5ff", "#e9d5ff", "#fecdd3"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#e9d5ff", "#fecdd3"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#e9d5ff",
                textColor: "#4c1d95",
                bgColor: "#f5f3ff",
                hoverBorderColor: "#a855f7",
                hoverTextColor: "#6d28d9",
                hoverBgColor: "#f3e8ff",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#e9d5ff",
                textColor: "#4c1d95",
                bgColor: "#faf5ff",
                hoverBorderColor: "#f472b6",
                hoverTextColor: "#9d174d",
                hoverBgColor: "#fce7f3",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 78,
                blur: 26,
                radius: 28,

            },
            textColor: "#4c1d95",
            hoverAnimation: "lift",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#fbcfe8",
            textColor: "#9d174d",
            bgColor: "#fdf2f8",
            hoverBorderColor: "#f472b6",
            hoverTextColor: "#9d174d",
            hoverBgColor: "#fce7f3",
            textAlign: "center",
        },
    },
    {
        id: "citrus-mist",
        name: "Citrus Mist",
        description: "Bright citrus warmth balanced with cool sky.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#fffbeb", "#fde68a", "#e0f2fe"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#fde68a", "#e0f2fe"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#fde68a",
                textColor: "#92400e",
                bgColor: "#fffbeb",
                hoverBorderColor: "#f59e0b",
                hoverTextColor: "#b45309",
                hoverBgColor: "#fef3c7",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#fde68a",
                textColor: "#92400e",
                bgColor: "#fffbeb",
                hoverBorderColor: "#f97316",
                hoverTextColor: "#9a3412",
                hoverBgColor: "#ffedd5",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 80,
                blur: 24,
                radius: 28,

            },
            textColor: "#92400e",
            hoverAnimation: "pop",
            hoverTransitionMs: 230,
        },
        customButtonStyle: {
            borderColor: "#bae6fd",
            textColor: "#0f172a",
            bgColor: "#f0f9ff",
            hoverBorderColor: "#38bdf8",
            hoverTextColor: "#075985",
            hoverBgColor: "#e0f2fe",
            textAlign: "center",
        },
    },
    {
        id: "sage-studio",
        name: "Sage Studio",
        description: "Soft stone neutrals with fresh sage accents.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#f8fafc", "#e2e8f0", "#d1fae5"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#e2e8f0", "#d1fae5"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#e2e8f0",
                textColor: "#065f46",
                bgColor: "#ffffff",
                hoverBorderColor: "#10b981",
                hoverTextColor: "#065f46",
                hoverBgColor: "#d1fae5",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#e2e8f0",
                textColor: "#0f172a",
                bgColor: "#ffffff",
                hoverBorderColor: "#10b981",
                hoverTextColor: "#065f46",
                hoverBgColor: "#d1fae5",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 82,
                blur: 26,
                radius: 28,

            },
            textColor: "#0f172a",
            hoverAnimation: "lift",
            hoverTransitionMs: 230,
        },
        customButtonStyle: {
            borderColor: "#bbf7d0",
            textColor: "#065f46",
            bgColor: "#ecfdf5",
            hoverBorderColor: "#34d399",
            hoverTextColor: "#065f46",
            hoverBgColor: "#d1fae5",
            textAlign: "center",
        },
    },
    {
        id: "coastal-blue",
        name: "Coastal Blue",
        description: "Sea-glass blues with breezy teal hovers.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#eff6ff", "#bfdbfe", "#a5f3fc"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#bfdbfe", "#a5f3fc"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#bfdbfe",
                textColor: "#1e3a8a",
                bgColor: "#eff6ff",
                hoverBorderColor: "#0ea5e9",
                hoverTextColor: "#0c4a6e",
                hoverBgColor: "#e0f2fe",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#bfdbfe",
                textColor: "#1e3a8a",
                bgColor: "#eff6ff",
                hoverBorderColor: "#38bdf8",
                hoverTextColor: "#0c4a6e",
                hoverBgColor: "#e0f2fe",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 80,
                blur: 28,
                radius: 28,

            },
            textColor: "#0f172a",
            hoverAnimation: "float",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#7dd3fc",
            textColor: "#0c4a6e",
            bgColor: "#e0f2fe",
            hoverBorderColor: "#38bdf8",
            hoverTextColor: "#0c4a6e",
            hoverBgColor: "#bae6fd",
            textAlign: "center",
        },
    },
    {
        id: "sunset-clay",
        name: "Sunset Clay",
        description: "Warm clay gradients with coral highlights.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#fff1f2", "#fecdd3", "#fed7aa"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#fecdd3", "#fed7aa"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#fecdd3",
                textColor: "#9f1239",
                bgColor: "#fff1f2",
                hoverBorderColor: "#fb7185",
                hoverTextColor: "#9f1239",
                hoverBgColor: "#ffe4e6",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#fed7aa",
                textColor: "#9a3412",
                bgColor: "#fff7ed",
                hoverBorderColor: "#fb7185",
                hoverTextColor: "#9f1239",
                hoverBgColor: "#ffe4e6",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 82,
                blur: 26,
                radius: 28,

            },
            textColor: "#7c2d12",
            hoverAnimation: "lift",
            hoverTransitionMs: 230,
        },
        customButtonStyle: {
            borderColor: "#fdba74",
            textColor: "#9a3412",
            bgColor: "#ffedd5",
            hoverBorderColor: "#fb7185",
            hoverTextColor: "#9f1239",
            hoverBgColor: "#ffe4e6",
            textAlign: "center",
        },
    },
    {
        id: "velvet-plum",
        name: "Velvet Plum",
        description: "Creamy lilac with plum accents.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#faf5ff", "#ede9fe", "#fce7f3"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#ede9fe", "#fce7f3"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#e9d5ff",
                textColor: "#6b21a8",
                bgColor: "#faf5ff",
                hoverBorderColor: "#a855f7",
                hoverTextColor: "#6b21a8",
                hoverBgColor: "#f3e8ff",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#e9d5ff",
                textColor: "#6b21a8",
                bgColor: "#faf5ff",
                hoverBorderColor: "#f472b6",
                hoverTextColor: "#9d174d",
                hoverBgColor: "#fce7f3",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 78,
                blur: 26,
                radius: 28,

            },
            textColor: "#4c1d95",
            hoverAnimation: "float",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#fbcfe8",
            textColor: "#9d174d",
            bgColor: "#fdf2f8",
            hoverBorderColor: "#f472b6",
            hoverTextColor: "#9d174d",
            hoverBgColor: "#fce7f3",
            textAlign: "center",
        },
    },
    {
        id: "graphite-mist",
        name: "Graphite Mist",
        description: "Clean grayscale with subtle indigo glow.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#f8fafc", "#e2e8f0", "#cbd5e1"],
            direction: "to bottom right",
        },
        cover: {
            type: "solid",
            color: "#e2e8f0",
        },
        theme: {
            iconStyle: {
                borderColor: "#cbd5e1",
                textColor: "#0f172a",
                bgColor: "#f8fafc",
                hoverBorderColor: "#6366f1",
                hoverTextColor: "#312e81",
                hoverBgColor: "#eef2ff",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#cbd5e1",
                textColor: "#0f172a",
                bgColor: "#f8fafc",
                hoverBorderColor: "#6366f1",
                hoverTextColor: "#312e81",
                hoverBgColor: "#eef2ff",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 84,
                blur: 24,
                radius: 28,

            },
            textColor: "#0f172a",
            hoverAnimation: "lift",
            hoverTransitionMs: 230,
        },
        customButtonStyle: {
            borderColor: "#c7d2fe",
            textColor: "#312e81",
            bgColor: "#eef2ff",
            hoverBorderColor: "#818cf8",
            hoverTextColor: "#312e81",
            hoverBgColor: "#e0e7ff",
            textAlign: "center",
        },
    },
    {
        id: "emerald-bay",
        name: "Emerald Bay",
        description: "Vivid emerald accents with soft sea glass.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#ecfdf5", "#d1fae5", "#a7f3d0"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#d1fae5", "#a7f3d0"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#d1fae5",
                textColor: "#047857",
                bgColor: "#ecfdf5",
                hoverBorderColor: "#10b981",
                hoverTextColor: "#065f46",
                hoverBgColor: "#d1fae5",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#d1fae5",
                textColor: "#047857",
                bgColor: "#ecfdf5",
                hoverBorderColor: "#22c55e",
                hoverTextColor: "#166534",
                hoverBgColor: "#dcfce7",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 80,
                blur: 26,
                radius: 28,

            },
            textColor: "#065f46",
            hoverAnimation: "pop",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#86efac",
            textColor: "#166534",
            bgColor: "#dcfce7",
            hoverBorderColor: "#22c55e",
            hoverTextColor: "#166534",
            hoverBgColor: "#bbf7d0",
            textAlign: "center",
        },
    },
    {
        id: "citrus-pop",
        name: "Citrus Pop",
        description: "Sunlit citrus with bright lime highlights.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#fffbeb", "#fef3c7", "#d9f99d"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#fef3c7", "#d9f99d"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#fde68a",
                textColor: "#92400e",
                bgColor: "#fffbeb",
                hoverBorderColor: "#a3e635",
                hoverTextColor: "#365314",
                hoverBgColor: "#ecfccb",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#fde68a",
                textColor: "#92400e",
                bgColor: "#fffbeb",
                hoverBorderColor: "#f59e0b",
                hoverTextColor: "#92400e",
                hoverBgColor: "#fef3c7",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 82,
                blur: 24,
                radius: 28,

            },
            textColor: "#92400e",
            hoverAnimation: "lift",
            hoverTransitionMs: 230,
        },
        customButtonStyle: {
            borderColor: "#bef264",
            textColor: "#365314",
            bgColor: "#ecfccb",
            hoverBorderColor: "#a3e635",
            hoverTextColor: "#365314",
            hoverBgColor: "#d9f99d",
            textAlign: "center",
        },
    },
    {
        id: "ruby-cream",
        name: "Ruby Cream",
        description: "Creamy base with ruby accents.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#fff5f5", "#fee2e2", "#fde68a"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#fee2e2", "#fde68a"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#fecaca",
                textColor: "#991b1b",
                bgColor: "#fff5f5",
                hoverBorderColor: "#ef4444",
                hoverTextColor: "#991b1b",
                hoverBgColor: "#fee2e2",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#fecaca",
                textColor: "#991b1b",
                bgColor: "#fff5f5",
                hoverBorderColor: "#f97316",
                hoverTextColor: "#9a3412",
                hoverBgColor: "#ffedd5",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 80,
                blur: 26,
                radius: 28,

            },
            textColor: "#991b1b",
            hoverAnimation: "float",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#fdba74",
            textColor: "#9a3412",
            bgColor: "#ffedd5",
            hoverBorderColor: "#f97316",
            hoverTextColor: "#9a3412",
            hoverBgColor: "#fed7aa",
            textAlign: "center",
        },
    },
    {
        id: "ice-blue",
        name: "Ice Blue",
        description: "Frosted blues with crisp slate text.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#f0f9ff", "#e0f2fe", "#e2e8f0"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#e0f2fe", "#e2e8f0"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#e0f2fe",
                textColor: "#0f172a",
                bgColor: "#f8fafc",
                hoverBorderColor: "#0ea5e9",
                hoverTextColor: "#075985",
                hoverBgColor: "#e0f2fe",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#e0f2fe",
                textColor: "#0f172a",
                bgColor: "#f8fafc",
                hoverBorderColor: "#38bdf8",
                hoverTextColor: "#075985",
                hoverBgColor: "#e0f2fe",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 84,
                blur: 24,
                radius: 28,

            },
            textColor: "#0f172a",
            hoverAnimation: "float",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#7dd3fc",
            textColor: "#075985",
            bgColor: "#e0f2fe",
            hoverBorderColor: "#38bdf8",
            hoverTextColor: "#075985",
            hoverBgColor: "#bae6fd",
            textAlign: "center",
        },
    },
    {
        id: "mocha-mousse",
        name: "Mocha Mousse",
        description: "Warm sand and coffee tones.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#fefaf5", "#fde8d7", "#f9dcc4"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#fde8d7", "#f9dcc4"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#f5e1d1",
                textColor: "#7c2d12",
                bgColor: "#fefaf5",
                hoverBorderColor: "#c2410c",
                hoverTextColor: "#7c2d12",
                hoverBgColor: "#fde8d7",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#f5e1d1",
                textColor: "#7c2d12",
                bgColor: "#fefaf5",
                hoverBorderColor: "#ea580c",
                hoverTextColor: "#7c2d12",
                hoverBgColor: "#fed7aa",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 82,
                blur: 24,
                radius: 28,

            },
            textColor: "#7c2d12",
            hoverAnimation: "lift",
            hoverTransitionMs: 230,
        },
        customButtonStyle: {
            borderColor: "#fed7aa",
            textColor: "#7c2d12",
            bgColor: "#ffedd5",
            hoverBorderColor: "#fb923c",
            hoverTextColor: "#7c2d12",
            hoverBgColor: "#fed7aa",
            textAlign: "center",
        },
    },
    {
        id: "midnight-neon",
        name: "Midnight Neon",
        description: "Dark base with electric cyan and magenta.",
        tone: "dark",
        background: {
            type: "gradient",
            colors: ["#0b1020", "#111827", "#1f1b3a"],
            direction: "to bottom right",
        },
        cover: {
            type: "solid",
            color: "#111827",
        },
        theme: {
            iconStyle: {
                borderColor: "#1f2937",
                textColor: "#e2e8f0",
                bgColor: "#0f172a",
                hoverBorderColor: "#22d3ee",
                hoverTextColor: "#0b1020",
                hoverBgColor: "#22d3ee",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#1f2937",
                textColor: "#f8fafc",
                bgColor: "#0f172a",
                hoverBorderColor: "#f472b6",
                hoverTextColor: "#0b1020",
                hoverBgColor: "#f472b6",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#0b1020",
                opacity: 76,
                blur: 26,
                radius: 28,

            },
            textColor: "#f8fafc",
            hoverAnimation: "float",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#f472b6",
            textColor: "#0b1020",
            bgColor: "#fce7f3",
            hoverBorderColor: "#22d3ee",
            hoverTextColor: "#0b1020",
            hoverBgColor: "#99f6e4",
            textAlign: "center",
        },
    },
    {
        id: "nordic-dawn",
        name: "Nordic Dawn",
        description: "Cool slate gradients with sharp indigo accents.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#f8fafc", "#e2e8f0", "#c7d2fe"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#e2e8f0", "#c7d2fe"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#cbd5e1",
                textColor: "#1e3a8a",
                bgColor: "#f8fafc",
                hoverBorderColor: "#6366f1",
                hoverTextColor: "#312e81",
                hoverBgColor: "#eef2ff",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#cbd5e1",
                textColor: "#1e3a8a",
                bgColor: "#f8fafc",
                hoverBorderColor: "#6366f1",
                hoverTextColor: "#312e81",
                hoverBgColor: "#eef2ff",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 84,
                blur: 24,
                radius: 28,

            },
            textColor: "#1e3a8a",
            hoverAnimation: "float",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#c7d2fe",
            textColor: "#312e81",
            bgColor: "#eef2ff",
            hoverBorderColor: "#818cf8",
            hoverTextColor: "#312e81",
            hoverBgColor: "#e0e7ff",
            textAlign: "center",
        },
    },
    {
        id: "lagoon",
        name: "Lagoon",
        description: "Crystal teal gradients with calm blue accents.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#ecfeff", "#cffafe", "#bae6fd"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#cffafe", "#bae6fd"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#bae6fd",
                textColor: "#0e7490",
                bgColor: "#ecfeff",
                hoverBorderColor: "#22d3ee",
                hoverTextColor: "#0e7490",
                hoverBgColor: "#cffafe",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#bae6fd",
                textColor: "#0e7490",
                bgColor: "#ecfeff",
                hoverBorderColor: "#38bdf8",
                hoverTextColor: "#075985",
                hoverBgColor: "#e0f2fe",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 80,
                blur: 26,
                radius: 28,

            },
            textColor: "#0e7490",
            hoverAnimation: "pop",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#7dd3fc",
            textColor: "#075985",
            bgColor: "#e0f2fe",
            hoverBorderColor: "#38bdf8",
            hoverTextColor: "#075985",
            hoverBgColor: "#bae6fd",
            textAlign: "center",
        },
    },
    {
        id: "terracotta",
        name: "Terracotta",
        description: "Earthy clay tones with soft rose.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#fff7ed", "#fed7aa", "#fecaca"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#fed7aa", "#fecaca"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#fed7aa",
                textColor: "#9a3412",
                bgColor: "#fff7ed",
                hoverBorderColor: "#f97316",
                hoverTextColor: "#9a3412",
                hoverBgColor: "#ffedd5",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#fed7aa",
                textColor: "#9a3412",
                bgColor: "#fff7ed",
                hoverBorderColor: "#fb7185",
                hoverTextColor: "#9f1239",
                hoverBgColor: "#ffe4e6",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 80,
                blur: 24,
                radius: 28,

            },
            textColor: "#9a3412",
            hoverAnimation: "lift",
            hoverTransitionMs: 230,
        },
        customButtonStyle: {
            borderColor: "#fecaca",
            textColor: "#9f1239",
            bgColor: "#ffe4e6",
            hoverBorderColor: "#fb7185",
            hoverTextColor: "#9f1239",
            hoverBgColor: "#fecdd3",
            textAlign: "center",
        },
    },
    {
        id: "orchid-ice",
        name: "Orchid Ice",
        description: "Cool orchid tones with icy highlights.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#fdf4ff", "#f5d0fe", "#e0e7ff"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#f5d0fe", "#e0e7ff"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#f5d0fe",
                textColor: "#6b21a8",
                bgColor: "#fdf4ff",
                hoverBorderColor: "#a855f7",
                hoverTextColor: "#6b21a8",
                hoverBgColor: "#f3e8ff",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#f5d0fe",
                textColor: "#6b21a8",
                bgColor: "#fdf4ff",
                hoverBorderColor: "#818cf8",
                hoverTextColor: "#3730a3",
                hoverBgColor: "#e0e7ff",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 78,
                blur: 26,
                radius: 28,

            },
            textColor: "#6b21a8",
            hoverAnimation: "float",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#e9d5ff",
            textColor: "#6b21a8",
            bgColor: "#f5f3ff",
            hoverBorderColor: "#a855f7",
            hoverTextColor: "#6b21a8",
            hoverBgColor: "#ede9fe",
            textAlign: "center",
        },
    },
    {
        id: "sakura-bloom",
        name: "Sakura Bloom",
        description: "Cherry blossom pinks with soft cream.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#fff1f2", "#ffe4e6", "#fef9c3"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#ffe4e6", "#fef9c3"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#fecdd3",
                textColor: "#be123c",
                bgColor: "#fff1f2",
                hoverBorderColor: "#f43f5e",
                hoverTextColor: "#be123c",
                hoverBgColor: "#ffe4e6",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#fecdd3",
                textColor: "#be123c",
                bgColor: "#fff1f2",
                hoverBorderColor: "#f59e0b",
                hoverTextColor: "#92400e",
                hoverBgColor: "#fef3c7",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 82,
                blur: 24,
                radius: 28,

            },
            textColor: "#be123c",
            hoverAnimation: "pop",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#fecdd3",
            textColor: "#be123c",
            bgColor: "#ffe4e6",
            hoverBorderColor: "#f43f5e",
            hoverTextColor: "#be123c",
            hoverBgColor: "#fecdd3",
            textAlign: "center",
        },
    },
    {
        id: "sunrise",
        name: "Sunrise",
        description: "Golden sunrise with clear sky blues.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#fffbeb", "#fde68a", "#bae6fd"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#fde68a", "#bae6fd"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#fde68a",
                textColor: "#92400e",
                bgColor: "#fffbeb",
                hoverBorderColor: "#38bdf8",
                hoverTextColor: "#075985",
                hoverBgColor: "#e0f2fe",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#fde68a",
                textColor: "#92400e",
                bgColor: "#fffbeb",
                hoverBorderColor: "#f97316",
                hoverTextColor: "#9a3412",
                hoverBgColor: "#ffedd5",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 80,
                blur: 24,
                radius: 28,

            },
            textColor: "#92400e",
            hoverAnimation: "lift",
            hoverTransitionMs: 230,
        },
        customButtonStyle: {
            borderColor: "#bae6fd",
            textColor: "#075985",
            bgColor: "#e0f2fe",
            hoverBorderColor: "#38bdf8",
            hoverTextColor: "#075985",
            hoverBgColor: "#bae6fd",
            textAlign: "center",
        },
    },
    {
        id: "desert-dune",
        name: "Desert Dune",
        description: "Sandstone neutrals with bronze highlights.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#fffbf5", "#fde8d7", "#fed7aa"],
            direction: "to bottom right",
        },
        cover: {
            type: "gradient",
            colors: ["#fde8d7", "#fed7aa"],
            direction: "to right",
        },
        theme: {
            iconStyle: {
                borderColor: "#fde8d7",
                textColor: "#92400e",
                bgColor: "#fffbf5",
                hoverBorderColor: "#d97706",
                hoverTextColor: "#92400e",
                hoverBgColor: "#fde8d7",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#fde8d7",
                textColor: "#92400e",
                bgColor: "#fffbf5",
                hoverBorderColor: "#ea580c",
                hoverTextColor: "#9a3412",
                hoverBgColor: "#fed7aa",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 82,
                blur: 24,
                radius: 28,

            },
            textColor: "#92400e",
            hoverAnimation: "float",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#fed7aa",
            textColor: "#92400e",
            bgColor: "#ffedd5",
            hoverBorderColor: "#f97316",
            hoverTextColor: "#9a3412",
            hoverBgColor: "#fed7aa",
            textAlign: "center",
        },
    },
    {
        id: "obsidian-dev",
        name: "Obsidian Dev",
        description: "Deep graphite with neon cyan accents.",
        tone: "dark",
        background: {
            type: "gradient",
            colors: ["#0b1020", "#111827", "#0f172a"],
            direction: "to bottom right",
        },
        cover: {
            type: "solid",
            color: "#0f172a",
        },
        theme: {
            iconStyle: {
                borderColor: "#1f2937",
                textColor: "#e2e8f0",
                bgColor: "#0f172a",
                hoverBorderColor: "#22d3ee",
                hoverTextColor: "#0f172a",
                hoverBgColor: "#22d3ee",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#1f2937",
                textColor: "#f8fafc",
                bgColor: "#111827",
                hoverBorderColor: "#22d3ee",
                hoverTextColor: "#0f172a",
                hoverBgColor: "#22d3ee",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#0b1020",
                opacity: 78,
                blur: 26,
                radius: 28,

            },
            textColor: "#f8fafc",
            hoverAnimation: "float",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#22d3ee",
            textColor: "#0f172a",
            bgColor: "#cffafe",
            hoverBorderColor: "#a855f7",
            hoverTextColor: "#0f172a",
            hoverBgColor: "#e9d5ff",
            textAlign: "center",
        },
    },
    {
        id: "night-owl",
        name: "Night Owl",
        description: "Inky navy with electric indigo highlights.",
        tone: "dark",
        background: {
            type: "gradient",
            colors: ["#0f172a", "#111827", "#1e1b4b"],
            direction: "to bottom right",
        },
        cover: {
            type: "solid",
            color: "#111827",
        },
        theme: {
            iconStyle: {
                borderColor: "#1f2937",
                textColor: "#e2e8f0",
                bgColor: "#111827",
                hoverBorderColor: "#818cf8",
                hoverTextColor: "#0f172a",
                hoverBgColor: "#818cf8",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#1f2937",
                textColor: "#f8fafc",
                bgColor: "#0f172a",
                hoverBorderColor: "#818cf8",
                hoverTextColor: "#0f172a",
                hoverBgColor: "#818cf8",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#0f172a",
                opacity: 76,
                blur: 26,
                radius: 28,

            },
            textColor: "#f8fafc",
            hoverAnimation: "lift",
            hoverTransitionMs: 230,
        },
        customButtonStyle: {
            borderColor: "#c7d2fe",
            textColor: "#1e1b4b",
            bgColor: "#e0e7ff",
            hoverBorderColor: "#f472b6",
            hoverTextColor: "#1e1b4b",
            hoverBgColor: "#fce7f3",
            textAlign: "center",
        },
    },
    {
        id: "forest-night",
        name: "Forest Night",
        description: "Deep pine with emerald glow.",
        tone: "dark",
        background: {
            type: "gradient",
            colors: ["#0b1020", "#0f172a", "#064e3b"],
            direction: "to bottom right",
        },
        cover: {
            type: "solid",
            color: "#0f172a",
        },
        theme: {
            iconStyle: {
                borderColor: "#1f2937",
                textColor: "#e2e8f0",
                bgColor: "#0f172a",
                hoverBorderColor: "#34d399",
                hoverTextColor: "#0f172a",
                hoverBgColor: "#34d399",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#1f2937",
                textColor: "#f8fafc",
                bgColor: "#0f172a",
                hoverBorderColor: "#34d399",
                hoverTextColor: "#0f172a",
                hoverBgColor: "#34d399",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#0b1020",
                opacity: 78,
                blur: 26,
                radius: 28,

            },
            textColor: "#f8fafc",
            hoverAnimation: "pop",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#86efac",
            textColor: "#0f172a",
            bgColor: "#bbf7d0",
            hoverBorderColor: "#22c55e",
            hoverTextColor: "#0f172a",
            hoverBgColor: "#86efac",
            textAlign: "center",
        },
    },
    {
        id: "neon-terminal",
        name: "Neon Terminal",
        description: "Developer-friendly black with neon green.",
        tone: "dark",
        background: {
            type: "gradient",
            colors: ["#020617", "#0b1020", "#111827"],
            direction: "to bottom right",
        },
        cover: {
            type: "solid",
            color: "#0b1020",
        },
        theme: {
            iconStyle: {
                borderColor: "#1f2937",
                textColor: "#f8fafc",
                bgColor: "#0b1020",
                hoverBorderColor: "#a3e635",
                hoverTextColor: "#0b1020",
                hoverBgColor: "#a3e635",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#1f2937",
                textColor: "#f8fafc",
                bgColor: "#0b1020",
                hoverBorderColor: "#a3e635",
                hoverTextColor: "#0b1020",
                hoverBgColor: "#a3e635",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#0b1020",
                opacity: 74,
                blur: 26,
                radius: 28,

            },
            textColor: "#f8fafc",
            hoverAnimation: "float",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#a3e635",
            textColor: "#0b1020",
            bgColor: "#ecfccb",
            hoverBorderColor: "#22d3ee",
            hoverTextColor: "#0b1020",
            hoverBgColor: "#cffafe",
            textAlign: "center",
        },
    },
    {
        id: "mono-ink",
        name: "Mono Ink",
        description: "Pure black with crisp white accents.",
        tone: "dark",
        background: {
            type: "solid",
            color: "#000000",
        },
        cover: {
            type: "solid",
            color: "#0a0a0a",
        },
        theme: {
            iconStyle: {
                borderColor: "#262626",
                textColor: "#f8fafc",
                bgColor: "#0a0a0a",
                hoverBorderColor: "#f8fafc",
                hoverTextColor: "#0a0a0a",
                hoverBgColor: "#f8fafc",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#262626",
                textColor: "#f8fafc",
                bgColor: "#0a0a0a",
                hoverBorderColor: "#f8fafc",
                hoverTextColor: "#0a0a0a",
                hoverBgColor: "#f8fafc",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#0a0a0a",
                opacity: 82,
                blur: 22,
                radius: 28,

            },
            textColor: "#f8fafc",
            hoverAnimation: "lift",
            hoverTransitionMs: 230,
        },
        customButtonStyle: {
            borderColor: "#f8fafc",
            textColor: "#0a0a0a",
            bgColor: "#f8fafc",
            hoverBorderColor: "#e5e7eb",
            hoverTextColor: "#0a0a0a",
            hoverBgColor: "#e5e7eb",
            textAlign: "center",
        },
    },
    {
        id: "noir-paper",
        name: "Noir Paper",
        description: "Minimal black and white with subtle gray.",
        tone: "dark",
        background: {
            type: "gradient",
            colors: ["#0a0a0a", "#111827", "#0a0a0a"],
            direction: "to bottom right",
        },
        cover: {
            type: "solid",
            color: "#111827",
        },
        theme: {
            iconStyle: {
                borderColor: "#3f3f46",
                textColor: "#fafafa",
                bgColor: "#111827",
                hoverBorderColor: "#fafafa",
                hoverTextColor: "#111827",
                hoverBgColor: "#fafafa",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#3f3f46",
                textColor: "#fafafa",
                bgColor: "#111827",
                hoverBorderColor: "#fafafa",
                hoverTextColor: "#111827",
                hoverBgColor: "#fafafa",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#111827",
                opacity: 78,
                blur: 22,
                radius: 28,

            },
            textColor: "#fafafa",
            hoverAnimation: "float",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#fafafa",
            textColor: "#111827",
            bgColor: "#fafafa",
            hoverBorderColor: "#d4d4d8",
            hoverTextColor: "#111827",
            hoverBgColor: "#d4d4d8",
            textAlign: "center",
        },
    },
    {
        id: "silverline",
        name: "Silverline",
        description: "Crisp grayscale with cool blue hovers.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#f8fafc", "#e5e7eb", "#d1d5db"],
            direction: "to bottom right",
        },
        cover: {
            type: "solid",
            color: "#e5e7eb",
        },
        theme: {
            iconStyle: {
                borderColor: "#d1d5db",
                textColor: "#111827",
                bgColor: "#f9fafb",
                hoverBorderColor: "#94a3b8",
                hoverTextColor: "#111827",
                hoverBgColor: "#e2e8f0",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#d1d5db",
                textColor: "#111827",
                bgColor: "#f9fafb",
                hoverBorderColor: "#94a3b8",
                hoverTextColor: "#111827",
                hoverBgColor: "#e2e8f0",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 86,
                blur: 24,
                radius: 28,

            },
            textColor: "#111827",
            hoverAnimation: "lift",
            hoverTransitionMs: 230,
        },
        customButtonStyle: {
            borderColor: "#cbd5f5",
            textColor: "#111827",
            bgColor: "#eef2ff",
            hoverBorderColor: "#94a3b8",
            hoverTextColor: "#111827",
            hoverBgColor: "#e2e8f0",
            textAlign: "center",
        },
    },
    {
        id: "pebble",
        name: "Pebble",
        description: "Warm stone grays with soft charcoal.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#f9fafb", "#e7e5e4", "#d6d3d1"],
            direction: "to bottom right",
        },
        cover: {
            type: "solid",
            color: "#e7e5e4",
        },
        theme: {
            iconStyle: {
                borderColor: "#d6d3d1",
                textColor: "#292524",
                bgColor: "#fafaf9",
                hoverBorderColor: "#a8a29e",
                hoverTextColor: "#292524",
                hoverBgColor: "#e7e5e4",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#d6d3d1",
                textColor: "#292524",
                bgColor: "#fafaf9",
                hoverBorderColor: "#a8a29e",
                hoverTextColor: "#292524",
                hoverBgColor: "#e7e5e4",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 86,
                blur: 24,
                radius: 28,

            },
            textColor: "#292524",
            hoverAnimation: "float",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#e7e5e4",
            textColor: "#292524",
            bgColor: "#f5f5f4",
            hoverBorderColor: "#a8a29e",
            hoverTextColor: "#292524",
            hoverBgColor: "#e7e5e4",
            textAlign: "center",
        },
    },
    {
        id: "fog",
        name: "Fog",
        description: "Airy light gray with soft slate accents.",
        tone: "light",
        background: {
            type: "gradient",
            colors: ["#f8fafc", "#e2e8f0", "#cbd5e1"],
            direction: "to bottom right",
        },
        cover: {
            type: "solid",
            color: "#e2e8f0",
        },
        theme: {
            iconStyle: {
                borderColor: "#cbd5e1",
                textColor: "#0f172a",
                bgColor: "#f8fafc",
                hoverBorderColor: "#64748b",
                hoverTextColor: "#0f172a",
                hoverBgColor: "#e2e8f0",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#cbd5e1",
                textColor: "#0f172a",
                bgColor: "#f8fafc",
                hoverBorderColor: "#64748b",
                hoverTextColor: "#0f172a",
                hoverBgColor: "#e2e8f0",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#ffffff",
                opacity: 84,
                blur: 24,
                radius: 28,

            },
            textColor: "#0f172a",
            hoverAnimation: "lift",
            hoverTransitionMs: 230,
        },
        customButtonStyle: {
            borderColor: "#cbd5e1",
            textColor: "#0f172a",
            bgColor: "#e2e8f0",
            hoverBorderColor: "#94a3b8",
            hoverTextColor: "#0f172a",
            hoverBgColor: "#cbd5e1",
            textAlign: "center",
        },
    },
    {
        id: "steel",
        name: "Steel",
        description: "Deep gray with cool metallic highlights.",
        tone: "dark",
        background: {
            type: "gradient",
            colors: ["#0f172a", "#111827", "#1f2937"],
            direction: "to bottom right",
        },
        cover: {
            type: "solid",
            color: "#111827",
        },
        theme: {
            iconStyle: {
                borderColor: "#374151",
                textColor: "#e5e7eb",
                bgColor: "#111827",
                hoverBorderColor: "#e5e7eb",
                hoverTextColor: "#111827",
                hoverBgColor: "#e5e7eb",
                radius: 999,
                textAlign: "center",
            },
            buttonStyle: {
                borderColor: "#374151",
                textColor: "#f3f4f6",
                bgColor: "#111827",
                hoverBorderColor: "#e5e7eb",
                hoverTextColor: "#111827",
                hoverBgColor: "#e5e7eb",
                radius: 18,
                textAlign: "center",
            },
            contentCard: {
                bgColor: "#0f172a",
                opacity: 76,
                blur: 22,
                radius: 28,

            },
            textColor: "#f3f4f6",
            hoverAnimation: "float",
            hoverTransitionMs: 240,
        },
        customButtonStyle: {
            borderColor: "#e5e7eb",
            textColor: "#111827",
            bgColor: "#f3f4f6",
            hoverBorderColor: "#d1d5db",
            hoverTextColor: "#111827",
            hoverBgColor: "#e5e7eb",
            textAlign: "center",
        },
    },
];

const radiusPresets = [
    { icon: 999, button: 18, card: 28 },
    { icon: 20, button: 16, card: 26 },
    { icon: 16, button: 14, card: 22 },
    { icon: 12, button: 10, card: 18 },
    { icon: 8, button: 8, card: 16 },
    { icon: 999, button: 999, card: 24 },
    { icon: 24, button: 20, card: 30 },
    { icon: 14, button: 12, card: 20 },
];

const lightCardPresets = [
    { bgColor: "#ffffff", opacity: 82, blur: 28, radius: 28 },
    { bgColor: "#f8fafc", opacity: 76, blur: 24, radius: 24 },
    { bgColor: "#fefce8", opacity: 78, blur: 20, radius: 20 },
    { bgColor: "#fdf2f8", opacity: 80, blur: 26, radius: 26 },
    { bgColor: "#ecfeff", opacity: 75, blur: 24, radius: 22 },
    { bgColor: "#eff6ff", opacity: 70, blur: 22, radius: 24 },
    { bgColor: "#f1f5f9", opacity: 68, blur: 18, radius: 18 },
    { bgColor: "#ffffff", opacity: 60, blur: 16, radius: 16 },
];

const darkCardPresets = [
    { bgColor: "#0b1220", opacity: 72, blur: 24, radius: 24 },
    { bgColor: "#0f172a", opacity: 78, blur: 20, radius: 20 },
    { bgColor: "#111827", opacity: 68, blur: 18, radius: 18 },
    { bgColor: "#030712", opacity: 70, blur: 22, radius: 22 },
    { bgColor: "#0a0a0a", opacity: 76, blur: 16, radius: 16 },
    { bgColor: "#0f172a", opacity: 62, blur: 14, radius: 14 },
];

export const themeTemplates: ThemeTemplate[] = (() => {
    let lightIndex = 0;
    let darkIndex = 0;

    return baseTemplates.map((template, index) => {
        const radiusPreset = radiusPresets[index % radiusPresets.length];
        const cardPreset =
            template.tone === "dark"
                ? darkCardPresets[darkIndex++ % darkCardPresets.length]
                : lightCardPresets[lightIndex++ % lightCardPresets.length];

        return {
            ...template,
            theme: {
                ...template.theme,
                iconStyle: {
                    ...template.theme.iconStyle,
                    radius: radiusPreset.icon,
                },
                buttonStyle: {
                    ...template.theme.buttonStyle,
                    radius: radiusPreset.button,
                },
                contentCard: {
                    ...template.theme.contentCard,
                    ...cardPreset,
                    radius: cardPreset.radius ?? radiusPreset.card,
                },
            },
        };
    });
})();
